POST  http://localhost:8080/todo 
Content-Type: application/json

{
  "title": "TODO 1",
  "description": "This is the first TODO"
}

###

GET http://localhost:8080/todo

###

GET http://localhost:8080/todo/61de1ffbf9cdc302c1e53501

###

DELETE  http://localhost:8080/todo/61de210d3a66b0f4fb773db5

###

PUT http://localhost:8080/todo/61ef86b5f5cb747a80e32f3f